version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - shopify_network
    # Removed depends_on since we're using external database

networks:
  shopify_network:
    driver: bridge