version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "5000:5000"  # You might want to change this or use nginx
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - shopify_network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Optional: Add nginx for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro  # For SSL certificates
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - shopify_network

networks:
  shopify_network:
    driver: bridge
