version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: component_app
    ports:
      - "6002:6002"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://component_user:component_app_123@192.168.100.35:5432/promo_database
      - PORT=6002
    # WebDAV configuration - no local mounting needed
    # All file operations go directly to WebDAV server via HTTP protocol
