"""Add properties table

Revision ID: add_properties_table
Revises: fix_picture_component_id_consistency
Create Date: 2025-01-15 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_properties_table'
down_revision = 'fix_picture_component_id_consistency'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('property_key', sa.String(length=100), nullable=False),
        sa.Column('display_name', sa.String(length=100), nullable=False),
        sa.Column('data_type', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('options', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('property_key'),
        schema='component_app'
    )
    
    # Create indexes for better performance
    op.create_index('idx_property_key', 'property', ['property_key'], schema='component_app')
    op.create_index('idx_property_data_type', 'property', ['data_type'], schema='component_app')
    op.create_index('idx_property_active', 'property', ['is_active'], schema='component_app')
    
    # Insert some default properties
    op.execute("""
        INSERT INTO component_app.property (property_key, display_name, data_type, description, is_active, options) VALUES
        ('material', 'Material', 'select', 'Material type of the component', true, '["cotton", "polyester", "wool", "silk", "linen", "denim", "satin", "velvet", "leather", "synthetic", "plastic", "metal", "wood", "bone", "mother of pearl", "acrylic", "brass", "steel", "nylon", "nickel", "aluminum", "cardboard", "paper", "vinyl", "fabric"]'),
        ('color', 'Color', 'select', 'Color of the component', true, '["black", "white", "red", "blue", "green", "yellow", "purple", "orange", "pink", "brown", "gray", "navy", "beige", "cream", "silver", "gold", "bronze", "copper", "chrome", "antique brass"]'),
        ('gender', 'Gender', 'multiselect', 'Target gender for the component', true, '["ladies", "men", "unisex", "all", "kids"]'),
        ('style', 'Style', 'multiselect', 'Style category of the component', true, '["casual", "formal", "sport", "winter", "summer", "vintage", "modern", "classic"]'),
        ('finish', 'Finish', 'text', 'Surface finish or treatment', true, '[]'),
        ('weight', 'Weight', 'text', 'Weight specification (e.g., 120gsm)', true, '[]'),
        ('size', 'Size', 'text', 'Size specification (e.g., 12mm)', true, '[]'),
        ('subcategory', 'Subcategory', 'text', 'Detailed category classification', true, '[]'),
        ('brand', 'Brand', 'select', 'Brand name', true, '[]'),
        ('subbrand', 'Subbrand', 'multiselect', 'Subbrand classification', true, '["MAR Sport", "MAR Classic", "MMC Pro", "MMC Casual", "UBL Premium", "UBL Basic"]')
    """)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_property_active', table_name='property', schema='component_app')
    op.drop_index('idx_property_data_type', table_name='property', schema='component_app')
    op.drop_index('idx_property_key', table_name='property', schema='component_app')
    op.drop_table('property', schema='component_app')
    # ### end Alembic commands ### 